name: Sync mobile MobileDev with Upstream dev

on:
  schedule:
    - cron: '1 0 * * *'  # 每天 UTC 时间 1 点执行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 授予写入内容的权限

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出一个临时目录用于获取上游代码
      - name: Checkout temporary directory for upstream code
        uses: actions/checkout@v3
        with:
          repository: 1pone/qwerty-learner
          ref: dev
          path: upstream-code

      # 检出您的fork仓库
      - name: Checkout your fork repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: your-fork

      # 配置Git身份
      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "418982+github-actions[bot]@users.noreply.github.com"

      # 检查并创建mobile_dev分支（如果需要）
      - name: Check and create mobile_dev branch
        run: |
          cd your-fork
          # 检查mobile_dev分支是否存在
          if git ls-remote --heads origin mobile_dev | grep -q mobile_dev; then
            echo "✅ mobile_dev分支已存在"
            git checkout mobile_dev
          else
            echo "❌ mobile_dev分支不存在，创建新的mobile_dev分支"
            git checkout -b mobile_dev
            git push origin mobile_dev
          fi

      # 同步上游代码到mobile_dev分支（避开工作流文件）
      - name: Sync upstream code to mobile_dev branch
        run: |
          # 定义源目录和目标目录
          UPSTREAM_DIR="${{ github.workspace }}/upstream-code"
          FORK_DIR="${{ github.workspace }}/your-fork"
          
          cd $FORK_DIR
          
          # 删除除了.git目录和.github/workflows目录之外的所有内容
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} \;
          
          # 如果.github/workflows目录不存在，创建它
          mkdir -p .github/workflows
          
          # 从上游复制所有文件，但排除.github/workflows目录
          rsync -av --progress $UPSTREAM_DIR/ $FORK_DIR/ --exclude='.git' --exclude='.github/workflows'

      # 提交更改
      - name: Commit changes
        run: |
          cd your-fork
          git add .
          git commit -m "Sync with upstream repository (1pone/qwerty-learner@dev)" || echo "没有更改需要提交"

      # 推送更改到dev分支
      - name: Push changes to mobile_dev branch
        run: |
          cd your-fork
          git push origin mobile_dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 可选的日志输出
      - name: Log sync status
        if: ${{ success() }}
        run: |
          echo "✅ 成功同步上游仓库更新！"

      - name: Log sync failure
        if: ${{ failure() }}
        run: |
          echo "❌ 同步上游仓库失败！"
          echo "请查看Actions日志了解详情。"
